# Generated by Django 5.0.6 on 2025-12-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre/Razón Social')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('OTRO', 'Otro')], default='DNI', max_length=4)),
                ('num_documento', models.CharField(max_length=15, unique=True, verbose_name='N° Documento')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=150, unique=True)),
                ('ruc', models.CharField(max_length=15, unique=True, verbose_name='RUC')),
                ('nombre_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion_productos', models.TextField(blank=True, null=True, verbose_name='Productos que ofrece')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
